#include <stdio.h>

#define associado inline
#define alinhaComo alignas
#define alinhaDo alignof
#define aumenta double
#define automatico auto
#define booleana bool
#define caso case
#define caractere char
#define charactere char
#define constante const
#define continua continue
#define curto short
#define decremento -=
#define definicaoDe typeof
#define definicaoTipo typedef
#define diferente !=
#define dividido /
#define divmento /=
#define e and
#define enderecodDe &
#define enumera enum
#define estatico static
#define externo extern
#define extenso long
#define examina scanf
#define faca do
#define falso false
#define flutuante float
#define imprima printf
#define incremento +=
#define igual ==
#define maior >
#define maiorIgual >=
#define menos -
#define menor <
#define menorIgual <=
#define multmento *= 
#define nao !
#define ou ||
#define padrao default
#define ponteiroNulo nullptr
#define principal main
#define quebra break
#define registra register
#define resto %
#define retorne return
#define restrito restrict
#define seletor switch
#define sinalizado signed
#define tamanhoDo sizeof
#define umiao union
#define verdadeiro true
#define vazio void
#define volatil volatile
#define vezes *
#define enquanto while

/* Estamos Abertos a sugestões */